config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
  	resources :reviews
  end
  root "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :section
	has_many :reviews

	has_attached_file :book_img, styles: { book_index: "250x300>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :user
 belongs_to :book
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:section].blank?
       @book = Book.all.order("created_at DESC")
     else
      section_id=Section.find_by(name:params[:section]).id
      @book=Book.where(:section_id => section_id).order ("created_at DESC")
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
    @sections=Section.all.map {|s| [s.name, s.id]}
  end

  # GET /books/1/edit
  def edit
    @sections=Section.all.map { |s| [s.name, s.id]  } 
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)
    @book.section_id=params[:section_id]

    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to root_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: root_path }
        @book.section_id=params[:section_id]
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_img, :title, :discription, :author,:section_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 before_action :find_book
 before_action :find_review, only:[:edit, :update, :destroy]
 
 def new
 	@review = Review.new
 end
 
 def create
 	@review = Review.new(review_params)
 	@review.book_id = @book.id
 	@review.user_id = current_user.id	
 	
 	if @review.save
 		redirect_to book_path(@book)
 	else
 		render 'new'
 	end
 end

 def edit
 	
 end

 def update
 	if @review.update(review_params)
 		redirect_to book_path(@book)
 	else
 		render 'edit'
 	end	
 end

 def destroy
 	@review.destroy
 	redirect_to book_path(@book)
 end
 
 private
    def review_params
 	params.require(:review).permit(:rating,:comment)
    end
 
    def find_book
 	@book = Book.find(params[:book_id])
    end

    def find_review
 	@review = Review.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
  <%= simple_form_for @book, :html=>{:multipart =>true} do |f|  %>
  <%= select_tag(:section_id, options_for_select(@sections), :prompt=>"Select Section")%>
  <%= f.file_field :book_img %>
 <%= f.input :title,lable:"Title of Book" %>
 <%= f.input :discription %>
 <%= f.input :author %>
 <%= f.button :submit %>
 <% end %>
  

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">

<h1>Editing Book</h1>


  <%= simple_form_for @book, :html=>{:multipart =>true} do |f|  %>
  <%= f.select :section_id, @sections %>
  <%= f.file_field :book_img %>
 <%= f.input :title,lable:"Title of Book" %>
 <%= f.input :discription %>
 <%= f.input :author %>
 <%= f.button :submit %>
 
 <% end %>
 

<%= link_to 'Show', @book %> 
<%= link_to 'Back', books_path %>

</div>
</div>

app/views/books/index.html.erb
<h1>Books</h1>
        <div class="row">
    
                  <% @book.each do |book| %>
                    <div class="col-md-3">
                      <a href="/books/<%= book.id%>">
                        <%=image_tag book.book_img.url(:book_index),class: "book" %> </a>
                        <h4 class="book-title"><%= book.title %></h4>
                        </div>
                    
                  <% end %>
  
        </div>            
<br>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">
		<h1>New Book</h1>

		<%= render 'form'%>

		<%= link_to 'Back', books_path %>
	</div>

</div>

app/views/books/show.html.erb
	<div class="row">   
		<div class="col-md-4">
		<%=image_tag @book.book_img.url(:book_show),class: "book-show"  %>
		</div>

		<div class="col-md-8">
				<div class="book-information">	
				  <h2 class="book-title"><%= @book.title %></h2>
				
			     
				  <h3 class="book-author"><%= @book.author %></h3>
				
				<p class="book-discrip">
				   <%= @book.discription %>
				</p>
				 				 				
				</div>

				<div class="row">
					<div class="col-md4">
						
						<%=render @book.reviews %>
						
						<div>
						<%= link_to "Add Review" , new_book_review_path(@book) %>
						</div>
						
					</div>
			</div>

		</div>

	</div>

	
    <% if user_signed_in? %>
	
	<% if @book.user_id==current_user.id %>
	
	<%= link_to 'Edit', edit_book_path(@book) %> 
	<%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>
	
	<% end %>

    <% end %>


<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadigBlast</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light"> 

      <div class="nav nav-header">
                  
          <%=link_to "ReadingBlast",books_path, class:"navbar-brand" %>
      </div>   

          <ul class="nav navbar-nav">
             <li class="nav-item" href="#"> <%=link_to "Sign Up ",new_user_registration_path %> </li>
             <% if user_signed_in? %>
             <li cclass="nav-item" href="#"><%=link_to " Sign Out",destroy_user_session_path, method: :delete %>
             </li>
              <% else %>
               <li class="nav-item" href="#"><%=link_to "Log in", new_user_session_path %></li>
              <%end%>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Sections <span class="caret"></span>     
                 </a>
                 <ul class="dropdown-menu" role="menu">
                  <% Section.all.each do |section| %>
                  <li>
                    <%= link_to section.name, books_path(section: section.name), class: "link" %>
                  </li>
                  <% end %> 
                 </ul>
                 
               </li>

          <% if user_signed_in? %>
          <li> <%=link_to "Add Book", new_book_path %></li>
                <% end %>
          </ul>    
    </div>
    </nav>



       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <div class="container">   
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@book, @book.reviews.build]) do |f| %>
<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score ="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>
		
		<%= link_to "Edit" , edit_book_review_path(review.book, review)%>
		<%= link_to "Delete" , book_review_path(review.book, review), method: :Delete, data: {confirm: "Are you Sure?"} %>
	<% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

	<h1>Edit Review</h1>
	<%= simple_form_for ([@book, @review]) do |f| %>
	<%= f.input :rating %>
	<%= f.input :comment %>
	<%= f.button :submit %>
	<% end %>

</div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h2>New Review</h2>
		<%= render 'form' %>

	</div>
</div>	